version: '3.8'

services:
  # Servidor Web com PHP e Apache
  web-server:
    image: php:8.2-apache
    container_name: yaripo_web
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    entrypoint: >
      sh -c "docker-php-ext-install mysqli && apache2-foreground"
    networks:
      - yaripo_net

  # Banco de Dados MySQL
  database:
    image: mariadb:10.6
    container_name: yaripo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yaripo_corp
    networks:
      - yaripo_net

networks:
  yaripo_net:
    driver: brigde

